language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
stages:
  - unit tests
  - name: deploy to staging
    if: branch = master
  - name: test staging
    if: branch = master
  - name: deploy to production
    if: branch = master
  - name: test production
    if: branch = master
jobs:
  include:
    - stage: unit tests
      script: npm test
    - stage: deploy to staging
      script: skip
      before_deploy: pip install --user awscli
      deploy:
        - provider: script
          script: npm run deploy:staging
          skip_cleanup: true
          on:
            branch: master
    - stage: test staging
      script: npm run test:staging
    - stage: deploy to production
      script: skip
      before_deploy: pip install --user awscli
      deploy:
        - provider: script
          script: npm run promote
          skip_cleanup: true
          on:
            branch: master
    - stage: test production
      script: npm run test:production
