dist: xenial
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - .cache
    - node_modules
    - public
notifications:
  email:
    on_success: change
    on_failure: change
git:
  depth: 1
before_install: npm i -g npm@latest
install: npm i
before_script: npm run build
script: npm test
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    repo: smockle/smockle.com
    branch: master
