dist: xenial
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
stages:
  - "Build and test local"
  - name: "Deploy to staging"
    if: branch = master AND repo = smockle/smockle.com
  - name: "Test staging"
    if: branch = master AND repo = smockle/smockle.com
  - name: "Deploy to production"
    if: branch = master AND repo = smockle/smockle.com
  - name: "Test production"
    if: branch = master AND repo = smockle/smockle.com
jobs:
  include:
    # BUILD AND TEST LOCAL
    - stage: "Build and test local"
      script: npm run build && npm test
    # DEPLOY TO STAGING
    - stage: "Deploy to staging"
      script: skip
      before_deploy: ls -a && pip install --user awscli
      deploy:
        - provider: script
          script: npm run deploy:staging
          skip_cleanup: true
          on:
            branch: master
            repo: smockle/smockle.com
            tags: false
    # TEST STAGING
    - stage: "Test staging"
      script: npm run test:staging
    # DEPLOY TO PRODUCTION
    - stage: "Deploy to production"
      script: skip
      before_deploy: ls -a && pip install --user awscli
      deploy:
        - provider: script
          script: npm run promote
          skip_cleanup: true
          on:
            branch: master
            repo: smockle/smockle.com
            tags: false
    # TEST PRODUCTION
    - stage: "Test production"
      script: npm run test:production
