baseURL = "https://www.smockle.com/"
languageCode = "en-us"
title = "Smockle"
theme = "smockle"
paginate = 1000
[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"