name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Test deployment
        run: "echo 'Test deployment!'"
