name: Workflows
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
