name: Deploy
on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get yarn cache
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - uses: actions/cache@v1
        with:
          path: .cache
          key: ${{ runner.os }}-gatsby-cache-${{ hashFiles('**/gatsby-config.js') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-

      - uses: actions/cache@v1
        with:
          path: public
          key: ${{ runner.os }}-public-${{ hashFiles('**/gatsby-config.js') }}
          restore-keys: |
            ${{ runner.os }}-public-

      - name: Install dependencies
        run: yarn install --ignore-optional

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn test

      - name: Deploy
        run: yarn run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
