name: Workflows
on:
  push:
    branches:
      - '[a-ln-zA-Z0-9\-_]*'
      - 'm[b-zA-Z0-9\-_]*'
      - 'ma[a-rt-zA-Z0-9\-_]*'
      - 'mas[a-su-zA-Z0-9\-_]*'
      - 'mast[a-df-zA-Z0-9\-_]*'
      - 'maste[a-qs-zA-Z0-9\-_]*'

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
