name: Workflows
on: [push]

jobs:
  build:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Test testing
        run: "echo 'Test testing!'"
